### ISSUE TITLE
[Registration]  Length of field "Visible name" should be at least 4 sybols

### ISSUE THREAD

**Issue by mozolnina** [zabrodas/mapandgo#1]
![screen shot 2017-12-03 at 10 16 47 am](https://user-images.githubusercontent.com/23036928/33528633-e0821e0e-d818-11e7-8de2-ac637f2aa047.png)
Length of field **"Visible name"** should be at least 4 sybols

**Comment by zabrodas** [comment]
Fixed. Min len is 2 chars now.
